### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by SergeoLacruz** [wolflu05/inventree-dymo-plugin#2]
Hi,
I installed the plugin using pip install inventree-dymo-plugin.
On serrver statr I see in the logs that it is loaded.
![log](https://github.com/wolflu05/inventree-dymo-plugin/assets/10836099/44772208-8778-41d3-8461-502ced7ea594)

I have a machine config
 
![admin](https://github.com/wolflu05/inventree-dymo-plugin/assets/10836099/a50fae77-e50e-4d29-8834-a13efdf43499)

I also enabled the InvenTreeDymoPlugin in the admin panel. But nothing more happens. The plugin does not show u in the settings. I think I am missng something in the setup Can you please advise. Thanks,

Michael

**Comment by wolflu05** [comment]
Hello Michael,

You need to use the platform UI Admin center (`https://your-instance/platform`) to manage machines. Presumably the settings are missing so the machine does not start. So navigate to the admin center > machines > create a dymo machine and configure it. (The Django admin should not be used for this task.)

If you have any further questions, I'm happy to assist.

Lukas

**Comment by SergeoLacruz** [comment]
Interesting, Never seen that before. It asks for username and password. My Inventree account does not work. Login failed tnaYa
Of course I created a machine using the django admin panel...
Things are starting to get complicated.

**Comment by wolflu05** [comment]
Yes, the complete UI is currently in a migration stage to a more modern UI using react. Normally if you are logged in in the current ui (CUI) you are automatically logged in in platform ui/the new ui (PUI) too. If not and if the login does not work either when entering the user+password, best will be to create an issue in the main repo to work out what's wrong. Please also provide version information and the used auth method then.

And yes, the machines management can exclusively be done through PUI.

**Comment by SergeoLacruz** [comment]
The setup works now. Thanks for the help. I set up the Dymo machine and assign it an IP address. I can select it for label printing. But when I print in the log I get:

``
WARNING: '<bound method DymoLabelPrinterDriver.print_labels of <inventree_dymo.InvenTreeDymoPlugin.DymoLabelPrinterDriver object at 0x7a8f9abfa9e0>>' not offloaded due to cannot pickle '_io.BufferedReader' object
cannot pickle '_io.BufferedReader' object
Saving setting 'InvenTreeUserSetting:NOTIFICATION_ERROR_REPORT_user:MichaelBuchmann' to cache
/home/michael/.local/lib/python3.10/site-packages/django/db/models/fields/__init__.py:1535: RuntimeWarning: DateTimeField NotificationEntry.updated received a naive datetime (2024-03-19 00:00:00) while time zone support is active.
  warnings.warn(
Gathering users for notification 'inventree.error_log'
Sending notification 'inventree.error_log' for 'Error object (1161)'
Triggering notification method 'ui_message'
Notify users via 'ui_message' for notification 'inventree.error_log' for 'Error object (1161)'
Notified 1 users via 'ui_message' for notification 'inventree.error_log' for 'Error object (1161)' successfully
[20/Mar/2024 15:48:42] "POST /api/label/part/3/print/?plugin=inventreelabelmachine&part%5B%5D=1425 HTTP/1.1" 200 48
``

Any Idea?

**Comment by SergeoLacruz** [comment]
It may be I accidentally deleted the label templates from the file system. I will look at this tomorrow.

**Comment by wolflu05** [comment]
No, you did everything right, there are actually two errors with the code when using workers. I'm working on a fix In inventree/InvenTree#6772 currently, but the second issue is a bit tricky.

**Comment by wolflu05** [comment]
This should be fixed now with inventree>=0.16.0 (Is currently scheduled to be released in a month or so) and this plugin in version >=1.0.0. (Note that v1.0.0 of this plugin will only work with Inventree>=0.16.0).
